title: "Charles Pourreau"
description: "Stratégie, modèles d'affaires et transformation par l'IA"
url: "https://charlespourreau.github.io"

remote_theme: "mmistakes/minimal-mistakes"

include:
  - _pages

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"

author:
  name: "Charles Pourreau"
  avatar: "/assets/images/portrait_carre.jpg"
  bio: "Stratégie d'entreprise à l'ère de l'IA"
  location: "France"
  links:
    - label: "LinkedIn"
      url: "https://fr.linkedin.com/in/charles-pourreau-30015940"
    - label: "GitHub"
      url: "https://github.com/charlespourreau"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      show_meta: true
